#A faire dans python (Terminal)
import turtle
turtle.getscreen()
turtle.shape("turtle")
turtle.color("red")
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
